### ISSUE TITLE
new kill confirm + combo sounds

### ISSUE THREAD

**Issue by DoctorGurke** [Eagle-One-Development/sbox-speed-dial#27]
I'd like to get a new kill confirm sound that isn't as high pitched/irritating. The new death sound works great for the player himself dying, but similar dial up sounds for every kill are getting a bit too much. We should probably get a sound that we can increase in intensity somehow depending on how high the current  combo is. On top of that also a similar sound that plays when the combo ends plus a special one that indicates this was your new max combo.

**Comment by beaumancer** [comment]
I closed this and added this to the winter update:

https://github.com/Eagle-One-Development/sbox-speed-dial/issues/38
